### ISSUE TITLE
Broken check due to server error

### ISSUE THREAD

**Issue by jonkoops** [siddharthkp/bundlesize2#31]
When running the `bundlesize` command I am getting a [server error](https://bundlesize-cache.vercel.app/?repo=jonkoops/Leaflet) when fetching the cached bundlesize:

```
> leaflet@1.7.1 bundlesize
> bundlesize --enable-github-checks

FetchError: invalid json response body at https://bundlesize-cache.vercel.app/?repo=jonkoops/Leaflet reason: Unexpected token A in JSON at position 0
    at /home/runner/work/Leaflet/Leaflet/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.get (/home/runner/work/Leaflet/Leaflet/node_modules/bundlesize2/src/pipeline/cache.js:9:12)
    at async Object.read (/home/runner/work/Leaflet/Leaflet/node_modules/bundlesize2/src/pipeline/cache.js:50:27)
    at async run (/home/runner/work/Leaflet/Leaflet/node_modules/bundlesize2/index.js:22:25) {
  type: 'invalid-json'
}

─ dist/leaflet.js
  ✖ dist/leaflet.js    140.35KB > 140 kb no compression  

─ dist/leaflet.js
  ✖ dist/leaflet.js    40.39KB > 40 kb gzip  

  2 checks failed   

Added check to GitHub
Error: Process completed with exit code 1.
```

For more information see the run in Github Actions: https://github.com/jonkoops/Leaflet/runs/4803353449

**Comment by siddharthkp** [comment]
👀 can reproduce, not sure why. I checked the database, the connection pool has more room 🤔 

```
{
"errorType":"Runtime.UnhandledPromiseRejection",
"errorMessage":"KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?",
"reason":{
  "errorType":"KnexTimeoutError",
  "errorMessage":"Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?",
  "name":"KnexTimeoutError"
}
```
