### ISSUE TITLE
Bundlesize2 checks failing on service

### ISSUE THREAD

**Issue by brandonb927** [siddharthkp/bundlesize2#40]
Since yesterday afternoon, Jan 17 2023 in the mid-afternoon, all Bundlesize2 checks seem to be failing with the error:

```
> bundlesize "--enable-github-checks"

/home/vsts/work/1/s/node_modules/node-fetch/lib/index.js:1519
			destroyStream(response.body, err);
			                       ^

TypeError: Cannot read property 'body' of null
    at /home/vsts/work/1/s/node_modules/node-fetch/lib/index.js:1519:27
    at IncomingMessage.<anonymous> (/home/vsts/work/1/s/node_modules/node-fetch/lib/index.js:1749:6)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:400:28)
    at TLSSocket.socketCloseListener (_http_client.js:441:11)
    at TLSSocket.emit (events.js:412:35)
    at net.js:686:12
    at TCP.done (_tls_wrap.js:564:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

We've had to disable Bundlesize in our CI as we rely on it, so I'm opening this issue to keep tabs on whether this issue in the service will be fixed.

Appreciate the hard work put into this project, we'd hate to see it go away silently 🦾

**Comment by TheBit** [comment]
Any news on this?

**Comment by siddharthkp** [comment]
Hello! I've fixed the cache service! Moved it from heroku to vercel

Also, if the service flops, it will not cause the CI to fail anymore. It would just skip comparing with base branch
